### ISSUE TITLE
Tabela em statement não aparece

### ISSUE THREAD

**Issue by chompatas** [az19djsd9823ui23/web-back-end#41]
![Captura de tela de 2019-08-15 21-16-57](https://user-images.githubusercontent.com/47321861/63134971-3e291e00-bfa2-11e9-9b86-701901dbb4fe.png)
Acredito que seja por conta do erro: django.db.utils.ProgrammingError: (1146, "Table 'databas.bitcoin_btcprofit' doesn't exist")

**Comment by joaoderocha** [comment]
O Statement só será criado se existir um depósito, saque, ou lucro relacionado a conta logada. 

Uma conta de superusuário não possui uma conta de Bitcoin vinculada, deve ser criada manualmente se necessário. O signal que faz isso, é ativado apenas durante o registro pelo site.

Verifique se está conectado ao banco de dados correto e se fez as migrações com o manage.py migrate.
